TOPDIR = ..

ASCIIDOC = osmostp-usermanual.adoc
include $(TOPDIR)/build/Makefile.asciidoc.inc
osmostp-usermanual.pdf: chapters/*.adoc
aoip-mgw-options.pdf: aoip-mgw-options.adoc mgw/*.msc

VTY_REFERENCE = osmostp-vty-reference.xml
include $(TOPDIR)/build/Makefile.vty-reference.inc

include $(TOPDIR)/build/Makefile.common.inc
